name: Build Calculadora de Precios

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  android:
    name: Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verificar código
        run: |
          echo "Commit compilado:"
          git rev-parse HEAD
          echo "Rama:"
          git branch --show-current
          echo "Contenido del proyecto:"
          ls -la
          echo "Contenido de lib:"
          ls -la lib
          echo "Formula RADEC:"
          grep -n "1.9604" lib/main.dart
          echo "Configuración de proveedores:"
          grep -n "ProviderSettingsPage" lib/main.dart

      - name: Generar archivos Android
        run: flutter create --platforms=android .

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-precios-android
          path: build/app/outputs/flutter-apk/app-release.apk


  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verificar código
        shell: pwsh
        run: |
          Write-Host "Commit compilado:"
          git rev-parse HEAD
          Write-Host "Formula RADEC:"
          Select-String -Path lib/main.dart -Pattern "1.9604"
          Write-Host "Configuración de proveedores:"
          Select-String -Path lib/main.dart -Pattern "ProviderSettingsPage"

      - name: Generar archivos Windows
        run: flutter create --platforms=windows .

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar Windows
        run: flutter build windows --release

      - name: Comprimir aplicación Windows
        shell: pwsh
        run: |
          Compress-Archive `
            -Path build/windows/x64/runner/Release/* `
            -DestinationPath CalculadoraPrecios-Windows.zip `
            -Force

      - name: Guardar aplicación Windows
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-precios-windows
          path: CalculadoraPrecios-Windows.zip
